name: Demo action file for testing

on: [push]

jobs:
  build:
    name: Sample
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Running a script
      run: |
        echo Learning actions through workflow
    
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Creating and running script
      run: touch script.py
    - name: Appending to file
      run: echo "print('Hello, world!')" >> script.py
    - name: Running the file
      run: python script.py
      
